<?php
error_reporting(0);
ini_set('display_errors', 0);

require "../auth/guard.php";
require_role(["administrator"]);
require "../config/database.php";

require "../lib/dompdf/dompdf_config.inc.php";

if (!isset($_GET["id"])) {
    die("Missing doctor ID");
}

$doctorId = (int)$_GET["id"];

/* date doctor */
$stmt = $pdo->prepare("
    SELECT d.first_name, d.last_name, d.specialization, d.phone, u.email
    FROM doctors d
    JOIN users u ON u.id = d.user_id
    WHERE u.id = ?
");
$stmt->execute([$doctorId]);
$doctor = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$doctor) {
    die("Doctor not found");
}

/* pacienți */
$stmt = $pdo->prepare("
    SELECT p.first_name, p.last_name, u.email
    FROM patient_assignments pa
    JOIN patients p ON p.user_id = pa.patient_id
    JOIN users u ON u.id = p.user_id
    WHERE pa.doctor_id = ?
      AND pa.active = 1
    ORDER BY p.last_name, p.first_name
");
$stmt->execute([$doctorId]);
$patients = $stmt->fetchAll(PDO::FETCH_ASSOC);

/* HTML PDF */
$html = '
<style>
body {
    font-family: DejaVu Sans, sans-serif;
    font-size: 12px;
}
h1 {
    text-align: center;
    color: #243b55;
}
.section {
    margin-bottom: 20px;
}
.label {
    font-weight: bold;
}
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 10px;
}
th, td {
    border: 1px solid #ccc;
    padding: 8px;
}
th {
    background: #f0f0f0;
}
.footer {
    margin-top: 30px;
    font-size: 10px;
    text-align: center;
    color: #666;
}
</style>

<h1>Doctor Profile</h1>

<div class="section">
    <p><span class="label">Name:</span> Dr. ' . htmlspecialchars($doctor["first_name"] . " " . $doctor["last_name"]) . '</p>
    <p><span class="label">Email:</span> ' . htmlspecialchars($doctor["email"]) . '</p>
    <p><span class="label">Specialization:</span> ' . htmlspecialchars($doctor["specialization"]) . '</p>
    <p><span class="label">Phone:</span> ' . htmlspecialchars($doctor["phone"]) . '</p>
</div>

<div class="section">
    <h3>Assigned Patients</h3>';

if (!$patients) {
    $html .= '<p>No patients assigned.</p>';
} else {
    $html .= '
    <table>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>';

    $i = 1;
    foreach ($patients as $p) {
        $html .= '
        <tr>
            <td>' . $i++ . '</td>
            <td>' . htmlspecialchars($p["first_name"] . " " . $p["last_name"]) . '</td>
            <td>' . htmlspecialchars($p["email"]) . '</td>
        </tr>';
    }

    $html .= '</table>';
}

$html .= '
</div>

<div class="footer">
    Generated by MEDCARE HUB ' . date("d.m.Y H:i") . '
</div>
';

/* PDF */
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();

$filename = "Doctor_Profile_" .
    preg_replace("/[^a-zA-Z]/", "_", $doctor["first_name"]) . "_" .
    preg_replace("/[^a-zA-Z]/", "_", $doctor["last_name"]) . ".pdf";

$dompdf->stream($filename, ["Attachment" => true]);
exit;
